#!/usr/bin/env python3
"""Canonical local record schemas for Trading Research System runtime files."""

from __future__ import annotations

from pathlib import Path
from typing import Mapping


CSV_SCHEMAS: Mapping[str, tuple[str, ...]] = {
    "broker_executions.csv": (
        "execution_id",
        "broker",
        "account_id",
        "trade_id",
        "order_id",
        "symbol",
        "underlying",
        "side",
        "quantity",
        "price",
        "fees",
        "currency",
        "execution_time",
        "instrument_type",
        "setup_id",
        "source_timestamp",
        "notes",
    ),
    "broker_orders.csv": (
        "order_id",
        "broker",
        "account_id",
        "symbol",
        "underlying",
        "side",
        "order_type",
        "status",
        "quantity",
        "filled_quantity",
        "limit_price",
        "avg_fill_price",
        "currency",
        "created_time",
        "updated_time",
        "instrument_type",
        "setup_id",
        "source_timestamp",
        "notes",
    ),
    "holdings.csv": (
        "ticker",
        "direction",
        "weight",
        "market_value",
        "asset_class",
        "sector",
        "beta",
        "rate_sensitivity",
        "usd_sensitivity",
        "policy_sensitivity",
        "notes",
    ),
    "intraday-watchlist.csv": (
        "date",
        "setup_id",
        "trade_id",
        "theme_id",
        "ticker",
        "underlying",
        "direction",
        "instrument_type",
        "analysis_timeframe",
        "trigger_timeframe",
        "setup_type",
        "key_levels",
        "trigger_zone",
        "invalidation",
        "current_status",
        "last_checked",
        "attention_reason",
        "execution_check_required",
        "notes",
    ),
    "portfolio_snapshot.csv": (
        "as_of",
        "broker",
        "account_id",
        "symbol",
        "underlying",
        "instrument_type",
        "direction",
        "quantity",
        "avg_cost",
        "market_price",
        "market_value",
        "currency",
        "unrealized_pnl",
        "realized_pnl",
        "delta_exposure",
        "notional_exposure",
        "theme_id",
        "source_timestamp",
        "notes",
    ),
    "research-note-log.csv": (
        "source",
        "date",
        "ticker",
        "author",
        "stance",
        "core_claim",
        "evidence_claimed",
        "primary_source_check",
        "counterargument",
        "confidence",
        "next_action",
    ),
    "research-report-log.csv": (
        "report_id",
        "source_priority",
        "source_type",
        "title",
        "ticker_or_theme",
        "author",
        "publication_date",
        "access_status",
        "stance",
        "horizon",
        "thesis",
        "verification_status",
        "next_check",
        "counter_thesis",
        "evidence_quality",
        "current_relevance",
        "plan_impact",
    ),
    "trade-plans.csv": (
        "date",
        "trade_id",
        "setup_id",
        "theme_id",
        "status",
        "ticker",
        "underlying",
        "direction",
        "instrument_type",
        "strategy_type",
        "analysis_timeframe",
        "trigger_timeframe",
        "setup_type",
        "entry_trigger",
        "trigger_zone",
        "invalidation",
        "stop_price",
        "target_1",
        "target_2",
        "ema_context",
        "price_action_context",
        "options_context",
        "macro_context",
        "risk_per_trade",
        "max_position_size",
        "time_stop",
        "notes",
    ),
    "trades.csv": (
        "trade_id",
        "parent_trade_id",
        "setup_id",
        "theme_id",
        "status",
        "entry_date",
        "exit_date",
        "symbol",
        "underlying",
        "direction",
        "trade_type",
        "product",
        "instrument_type",
        "analysis_timeframe",
        "trigger_timeframe",
        "setup_tag",
        "signal_quality",
        "confidence",
        "entry_price",
        "stop_price",
        "target_price",
        "quantity",
        "cost",
        "fees",
        "pnl",
        "risk_amount",
        "planned_R",
        "realized_R",
        "outcome",
        "mistake_tag",
        "setup_review",
        "entry_review",
        "exit_review",
        "lesson",
        "review_raw",
        "chart_link",
        "currency",
        "broker",
        "account_id",
        "execution_id",
    ),
    "watchlist.csv": (
        "ticker",
        "macro_fit",
        "company_quality",
        "valuation",
        "catalyst",
        "technical_setup",
        "liquidity",
        "risk_penalty",
        "thesis",
        "macro_note",
        "catalyst_note",
        "risk_note",
        "timing_condition",
        "next_check",
    ),
}

DAILY_TEMPLATE_TARGETS: Mapping[str, str] = {
    "watchlist.csv": "watchlist.csv",
    "trade-plans.csv": "trade-plans.csv",
    "intraday-watchlist.csv": "intraday-watchlist.csv",
    "trades.csv": "trades.csv",
    "holdings.csv": "portfolio.csv",
    "portfolio_snapshot.csv": "portfolio_snapshot.csv",
    "broker_executions.csv": "broker_executions.csv",
    "broker_orders.csv": "broker_orders.csv",
    "research-note-log.csv": "research-note-log.csv",
    "research-report-log.csv": "research-report-log.csv",
    "daily-macro-checklist.md": "daily-macro-checklist.md",
    "daily-market-tracking.md": "daily-market-tracking.md",
    "reviews.md": "reviews.md",
}


def template_dir_from_script(script_path: str | Path) -> Path:
    return Path(script_path).resolve().parents[1] / "assets" / "templates"
